Repository AY2021S2-CS2113T-F08-3/tp, pull requests merged in 2021-03, with the labels that each got.

#26 deleted sort by stars & added time to Review
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/review/Review.java
  src/main/java/seedu/connoisseur/sorter/SortByDateEarliest.java
  src/main/java/seedu/connoisseur/sorter/SortByDateLatest.java
Labels: priority.Medium, type.Bug

#28 removed seconds from time & added view command
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/messages/Messages.java
  src/main/java/seedu/connoisseur/parser/Parser.java
  src/main/java/seedu/connoisseur/review/Review.java
  src/main/java/seedu/connoisseur/sorter/SortByDateEarliest.java
  src/main/java/seedu/connoisseur/sorter/SortByDateLatest.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.Medium, type.Bug

#30 Add more help messages for other features
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/messages/Messages.java
  src/main/java/seedu/connoisseur/parser/Parser.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.Medium

#41 Implemented assert viewReview() method CommandList
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
Labels: priority.High, type.Task

#45 Added Edit feature, to edit existing review in the list
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/messages/Messages.java
  src/main/java/seedu/connoisseur/parser/Parser.java
  src/main/java/seedu/connoisseur/review/Review.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.High, type.Story

#61 added reveiw and reco mode
  src/main/java/seedu/connoisseur/Connoisseur.java
  src/main/java/seedu/connoisseur/messages/Messages.java
  src/main/java/seedu/connoisseur/parser/Parser.java
Labels: priority.High, type.Enhancement

#66 Added location recommendation
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/messages/Messages.java
  src/main/java/seedu/connoisseur/parser/Parser.java
  src/main/java/seedu/connoisseur/recommendation/Recommendation.java
  src/main/java/seedu/connoisseur/storage/Storage.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.Low, type.Enhancement

#68 added border when listing recommendation and review and when viewing …
  src/main/java/seedu/connoisseur/commandlist/CommandList.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.Low, type.Enhancement

#78 added edit feature to recommendation list
  src/main/java/seedu/connoisseur/commands/Commands.java
  src/main/java/seedu/connoisseur/commands/RecommendationList.java
  src/main/java/seedu/connoisseur/commands/ReviewList.java
  src/main/java/seedu/connoisseur/parser/Parser.java
  src/main/java/seedu/connoisseur/recommendation/Recommendation.java
  src/main/java/seedu/connoisseur/ui/Ui.java
Labels: priority.High, type.Enhancement, type.Story
